Added depositAndTransfer to VeilEther.
veilco/veil-contracts pull request #4
Opened 2019-01-09 17:24 UTC by tomcbean

2019-01-11 14:30 UTC, mertcelebi commented
This looks good @tomcbean, thank you for the PR. I'll add a similar method to `VirtualAugurShares` as well. 

Unfortunately, the production version of `VeilEther` is already deployed, and it would be hard to swap. What's the use case for this change on your end?

2019-01-11 14:35 UTC, mertcelebi requested changes

2019-01-11 14:35 UTC, mertcelebi commented on contracts/VeilEther.sol
> +  function depositAndTransfer(address _target) public payable returns (bool) {
This looks good. I know it's super simple, but do you mind adding tests before we merge?

2019-02-27 22:04 UTC, mertcelebi commented
Closing this due to inactivity.

2019-02-27 22:04 UTC, closed without merging

2019-02-28 03:47 UTC, tomcbean commented
Sorry, I lost track of this. I thought it useful to include this additional function, but since the mainnet contract is already deployed, we can make due without. Thanks.